import { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import GeminiOrb from '../animations/GeminiOrb';
import ParticleBackground from '../animations/ParticleBackground';
import Button from '../components/ui/Button';
import GeminiBadge from '../components/GeminiBadge';

gsap.registerPlugin(ScrollTrigger);

const FEATURES = [
  { icon: 'brain',           color: '#4285F4', title: 'Autonomous Planning',      desc: 'Describe your goal. Gemini builds a complete hour-by-hour action plan instantly.' },
  { icon: 'refresh',         color: '#8B5CF6', title: 'Adaptive Replanning',    desc: 'Miss a step? LifeSaver AI automatically rebuilds your plan to still hit the deadline.' },
  { icon: 'clock',           color: '#FBBC04', title: 'Morning AI Briefs',      desc: 'Wake up to a personalized daily priority brief generated by Gemini at 7AM.' },
  { icon: 'calendar-event',  color: '#34A853', title: 'Calendar Auto-Sync',     desc: 'Every step syncs to Google Calendar automatically. Zero manual effort.' }
];

const Landing = () => {
  const featuresRef = useRef(null);

  useEffect(() => {
    // GSAP scroll-triggered reveal for feature cards - Completely intact
    const cards = featuresRef.current?.querySelectorAll('.feature-card');
    if (!cards) return;

    cards.forEach((card, i) => {
      gsap.fromTo(card,
        { y: 60, opacity: 0 },
        {
          y: 0, opacity: 1, duration: 0.7,
          delay: i * 0.1,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: card,
            start:   'top 85%',
            toggleActions: 'play none none reverse'
          }
        }
      );
    });

    return () => ScrollTrigger.getAll().forEach(t => t.kill());
  }, []);

  return (
    <div className="relative min-h-screen overflow-hidden bg-[#0D1B2A]">
      
      {/* ========================================================================= */}
      {/* 1. IMMERSIVE BACKDROP LAYER                                               */}
      {/* ========================================================================= */}
      {/* Standard background engine layers */}
      <ParticleBackground />
      
      {/* Fullscreen 3D Ambient Orb Vector Mount */}
      <div className="absolute inset-0 z-0 w-screen h-screen overflow-hidden pointer-events-none opacity-30 flex items-center justify-center">
        <GeminiOrb size="100%" />
      </div>

      {/* ========================================================================= */}
      {/* 2. FOREGROUND CONTENT MATRIX (All architecture completely identical)       */}
      {/* ========================================================================= */}
      {/* Navbar Layer */}
      <nav className="relative z-20 flex items-center justify-between px-8 py-5">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-gblu to-gpurp
            flex items-center justify-center shadow-glow">
            <i className="ti ti-bolt text-white text-sm" />
          </div>
          <span className="font-bold text-white text-lg">LifeSaver AI</span>
        </div>
        <div className="flex items-center gap-3">
          <Link to="/login">
            <Button variant="ghost" size="sm">Sign In</Button>
          </Link>
          <Link to="/register">
            <Button size="sm" icon="rocket">Get Started</Button>
          </Link>
        </div>
      </nav>

      {/* Hero Content Section */}
      <section className="relative z-10 flex flex-col items-center justify-center
        min-h-[90vh] text-center px-6 py-12">

        {/* Floating badge anchor element */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="mb-6 mt-12"
        >
          <GeminiBadge size="md" />
        </motion.div>

        {/* Main Brand Headline */}
        <motion.h1
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5, duration: 0.8 }}
          className="text-5xl md:text-7xl font-black leading-none mb-6 max-w-4xl tracking-tight"
        >
          <span className="bg-gradient-to-r from-white to-[#00B4D8] bg-clip-text text-transparent">Your AI doesn't</span>
          <br />
          <span className="text-white">just remind you.</span>
          <br />
          <span className="bg-gradient-to-r from-[#00B4D8] to-[#06D6A0] bg-clip-text text-transparent">It plans for you.</span>
        </motion.h1>

        {/* Sub-text summary block */}
        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.7 }}
          className="text-white/60 text-lg md:text-xl max-w-2xl mb-10 leading-relaxed"
        >
          Describe any goal with a deadline. LifeSaver AI autonomously breaks it into
          a step-by-step plan, adapts when you fall behind, and syncs everything
          to Google Calendar — all without you lifting a finger.
        </motion.p>

        {/* Main CTA Nav Gateways */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.9 }}
          className="flex items-center gap-4 flex-wrap justify-center"
        >
          <Link to="/register">
            <Button variant="gradient" size="lg" icon="rocket">
              Start for free
            </Button>
          </Link>
          <Link to="/login">
            <Button variant="ghost" size="lg" icon="play">
              Watch demo
            </Button>
          </Link>
        </motion.div>
      </section>

      {/* Feature Reveal section with active GSAP hooks intact */}
      <section ref={featuresRef} className="relative z-10 px-6 pb-32">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-black text-white mb-4">
              Built different.<br />
              <span className="bg-gradient-to-r from-white to-[#00B4D8] bg-clip-text text-transparent">Powered by Gemini.</span>
            </h2>
            <p className="text-white/50 max-w-lg mx-auto">
              This is not another to-do app. This is an autonomous AI agent
              that takes over your productivity.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            {FEATURES.map((f, i) => (
              <div
                key={i}
                className="feature-card glass border border-white/10 rounded-2xl p-6
                  hover:border-white/20 transition-all duration-300
                  hover:shadow-glow group"
              >
                <div
                  className="w-12 h-12 rounded-xl flex items-center justify-center mb-4
                    transition-all duration-300 group-hover:scale-110"
                  style={{ background: `${f.color}22`, color: f.color }}
                >
                  <i className={`ti ti-${f.icon} text-2xl`} />
                </div>
                <h3 className="font-bold text-white text-lg mb-2">{f.title}</h3>
                <p className="text-white/50 text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};

export default Landing;